#!/usr/bin/env bash
# ClawBot server deployment script. Run it on the VPS host.
#
# Usage:
#   REPO_URL="https://github.com/JHPatchouli/clawbot-roleplay.git" \
#   SSH_PUBKEY="ssh-ed25519 AAAA... you@host" \
#   bash deploy/vps-setup.en.sh
#
# Optional variables:
#   BRANCH      default: main
#   APP_DIR     default: /opt/clawbot
#   SSH_BIND    default: 127.0.0.1; use 0.0.0.0 only with firewall restrictions
#   SSH_PORT    default: 2222
#   LOGIN_PORT  default: 8080
#   DEV         default: 1 mounts source and enables reload; 0 uses the image
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/clawbot}"
mkdir -p "$APP_DIR/data"
CFG_FILE="$APP_DIR/data/deploy.env"

if [ -f "$CFG_FILE" ]; then
  while IFS='=' read -r key value; do
    key="$(printf '%s' "$key" | tr -d '[:space:]')"
    case "$key" in
      BRANCH|SSH_BIND|SSH_PORT|LOGIN_PORT|DEV|REPO_URL) ;;
      *) continue ;;
    esac
    if eval "[ -z \"\${$key:-}\" ]"; then
      export "$key=$value"
    fi
  done < "$CFG_FILE"
  echo "==> 0/5 loaded previous settings: $CFG_FILE"
fi

REPO_URL="${REPO_URL:-}"
BRANCH="${BRANCH:-main}"
SSH_PUBKEY="${SSH_PUBKEY:-}"
SSH_BIND="${SSH_BIND:-127.0.0.1}"
SSH_PORT="${SSH_PORT:-2222}"
LOGIN_PORT="${LOGIN_PORT:-8080}"
DEV="${DEV:-1}"

if [ -z "$REPO_URL" ]; then
  echo "Error: REPO_URL is required." >&2
  echo "Example: REPO_URL=https://github.com/JHPatchouli/clawbot-roleplay.git bash $0" >&2
  exit 1
fi

echo "==> 1/5 preparing $BRANCH"
if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" fetch --all --prune
  git -C "$APP_DIR" checkout "$BRANCH"
  git -C "$APP_DIR" pull --ff-only
else
  git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
fi
cd "$APP_DIR"

KEY_DIR="$APP_DIR/data/ssh"
KEY_FILE="$KEY_DIR/authorized_keys"
mkdir -p "$KEY_DIR"
chmod 700 "$KEY_DIR"
touch "$KEY_FILE"
chmod 600 "$KEY_FILE"
if [ -n "$SSH_PUBKEY" ]; then
  printf '%s\n' "$SSH_PUBKEY" >> "$KEY_FILE"
fi
tr -d '\r' < "$KEY_FILE" | sed '/^[[:space:]]*$/d' | sort -u > "$KEY_FILE.tmp"
mv "$KEY_FILE.tmp" "$KEY_FILE"
chmod 600 "$KEY_FILE"
SSH_PUBKEY="$(cat "$KEY_FILE")"
if [ -z "$SSH_PUBKEY" ]; then
  echo "Error: $KEY_FILE is empty and SSH_PUBKEY was not provided." >&2
  exit 1
fi
echo "==> 1.5/5 public keys: $KEY_FILE ($(wc -l < "$KEY_FILE") entries)"

echo "==> 2/5 building image"
docker build -t clawbot:dev .

echo "==> 3/5 starting container"
if [ "$SSH_BIND" = "127.0.0.1" ]; then
  echo "    SSH is bound to 127.0.0.1 and is not reachable from the public network." >&2
  echo "    For direct access, rerun with SSH_BIND=0.0.0.0 and restrict the source IPs." >&2
fi

docker rm -f clawbot >/dev/null 2>&1 || true
RUN_ARGS=(
  -d --name clawbot
  --restart unless-stopped
  -p "${SSH_BIND}:${SSH_PORT}:22"
  -p "127.0.0.1:${LOGIN_PORT}:8080"
  -v "$APP_DIR/data:/app/data"
  -e TZ=Asia/Shanghai
  -e DATA_DIR=/app/data
  -e LOG_LEVEL=info
  -e LOGIN_PAGE_ENABLED=1
  -e LOGIN_PAGE_HOST=127.0.0.1
  -e LOGIN_PAGE_PORT=8080
  -e "SSH_AUTHORIZED_KEYS=${SSH_PUBKEY}"
)
if [ "$DEV" = "1" ]; then
  echo "    DEV=1: mounting source with node --watch"
  RUN_ARGS+=(-v "$APP_DIR/src:/app/src" -v "$APP_DIR:/repo")
  docker run "${RUN_ARGS[@]}" clawbot:dev node --watch src/index.js
else
  docker run "${RUN_ARGS[@]}" clawbot:dev
fi

echo "==> 4/5 checking container"
sleep 2
if ! docker ps --filter name=clawbot --filter status=running -q | grep -q .; then
  echo "Error: container is not running. Last 40 log lines:" >&2
  docker logs --tail 40 clawbot 2>&1 || true
  exit 1
fi
docker ps --filter name=clawbot --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'

umask 077
cat > "$CFG_FILE" <<EOF
# Generated by the deployment script. Values here become defaults next time.
BRANCH=$BRANCH
SSH_BIND=$SSH_BIND
SSH_PORT=$SSH_PORT
LOGIN_PORT=$LOGIN_PORT
DEV=$DEV
REPO_URL=$REPO_URL
EOF
chmod 600 "$CFG_FILE"

echo "==> 5/5 complete"
echo "Logs:    docker logs -f clawbot"
echo "SSH:     ssh -p ${SSH_PORT} root@${SSH_BIND}"
echo "Tunnel:  ssh -L ${LOGIN_PORT}:127.0.0.1:${LOGIN_PORT} -p ${SSH_PORT} root@${SSH_BIND}"
echo "Keys:    ${KEY_FILE}"
